<?php

namespace app\controllers;

use Yii;
use yii\web\NotFoundHttpException;

class Controller extends \yii\web\Controller
{
    const ALERT_ERROR = 'error';
    const ALERT_DANGER = 'danger';
    const ALERT_SUCCESS = 'success';
    const ALERT_INFO = 'info';
    const ALERT_WARNING = 'warning';

    public $userId;

    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {
        if(Yii::$app->user->isGuest){
            Yii::$app->end(Yii::$app->response->exitStatus, $this->redirect(['site/login']));
        }

        $this->userId = Yii::$app->user->id;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 异常提示
     * @param string $message
     * @throws NotFoundHttpException
     */
    public function exception($message = '')
    {
        throw new NotFoundHttpException($message);
    }

    /**
     * alert提示
     * @param string $message
     * @param string $type
     */
    public function alert($message, $type = self::ALERT_DANGER)
    {
        if($message){
            Yii::$app->session->setFlash($type, $message);
        }
    }
}
